# env needed for release:
#  - VERSION
#  - GITHUB_TOKEN

project_name: aetherfs

snapshot:
  name_template: "{{ .ShortCommit }}"

builds:
  - id: aetherfs
    main: ./main.go
    binary: aetherfs
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - linux
    goarch:
      - amd64
      - arm64
    hooks:
      post: ./scripts/dist-proto.sh

archives:
  - id: aetherfs
    name_template: "aetherfs_{{ .Os }}_{{ .Arch }}"
    builds:
      - aetherfs

checksum:
  name_template: 'aetherfs_checksums.txt'
  extra_files:
    - glob: "**/aetherfs_proto.tar.gz"

release:
  header: ""
  footer: ""
