version: "3.8"

services:
  minio:
    image: minio/minio
    ports:
      - 9000:9000
      - 9090:9090
    command:
      - server
      - /data
      - --console-address
      - ":9090"

  server:
    image: ${SKAFFOLD_DEFAULT_REPO:-ghcr.io/mjpitz}/aetherfs
    ports:
      - 8080:8080
    environment:
      STORAGE_DRIVER: s3
      STORAGE_S3_ENDPOINT: minio:9000
      STORAGE_S3_ACCESS_KEY_ID: minioadmin
      STORAGE_S3_SECRET_ACCESS_KEY: minioadmin
      STORAGE_S3_BUCKET: aetherfs-data
    command:
      - run
      - hub
