version: "3.8"

services:
  minio:
    image: minio/minio
    ports:
      - "9090:9090"
    command:
      - server
      - /data
      - --console-address
      - ":9090"

  public-deployment:
    image: ${SKAFFOLD_DEFAULT_REPO:-ghcr.io/mjpitz}/aetherfs
    ports:
      - "8080:8080"
      - "2049:2049"
    environment:
      STORAGE_DRIVER: s3
      STORAGE_S3_ENDPOINT: minio:9000
      STORAGE_S3_ACCESS_KEY_ID: minioadmin
      STORAGE_S3_SECRET_ACCESS_KEY: minioadmin
      STORAGE_S3_BUCKET: aetherfs-public-data
    command:
      - run
      - --web_enable
      - --nfs_enable

  private-deployment:
    image: ${SKAFFOLD_DEFAULT_REPO:-ghcr.io/mjpitz}/aetherfs
    ports:
      - "8090:8080"
    environment:
      STORAGE_DRIVER: s3
      STORAGE_S3_ENDPOINT: minio:9000
      STORAGE_S3_ACCESS_KEY_ID: minioadmin
      STORAGE_S3_SECRET_ACCESS_KEY: minioadmin
      STORAGE_S3_BUCKET: aetherfs-private-data
    command:
      - run
      - --web_enable
      - --tls_enable
      - --tls_cert_path=/var/lib/aetherfs/conf
      - --auth_type=basic
      - --basic_password_file=/var/lib/aetherfs/conf/passwords.csv
    volumes:
      - ./deploy/docker-compose:/var/lib/aetherfs/conf:ro
