apiVersion: v1
kind: Service
metadata:
  name: {{ include "aetherfs-hub.fullname" . }}
  labels:
    {{- include "aetherfs-hub.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  {{- if .Values.service.clusterIP }}
  clusterIP: {{ .Values.service.clusterIP }}
  {{- end }}
  ports:
    - port: 8080
      targetPort: http
      protocol: TCP
      name: http
    {{- if .Values.nfs.enabled }}
    - port: 2049
      targetPort: nfs
      protocol: TCP
      name: nfs
    {{- end }}
  selector:
    {{- include "aetherfs-hub.selectorLabels" . | nindent 4 }}
