apiVersion: v2
type: application
name: dex
description: A Helm chart for deploying Dex, a federated identity provider.
version: 0.0.0
appVersion: 0.0.0
dependencies:
  - repository: https://charts.dexidp.io
    name: dex
    version: 0.5.0
    condition: dex.enabled
