apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ include "aetherfs-datasets.fullname" . }}
  labels:
    {{- include "aetherfs-datasets.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadOnlyMany
  capacity:
    storage: 1Mi
  persistentVolumeReclaimPolicy: Delete
  nfs:
    path: /mount
    server: {{ .Values.nfs.server }}
    readOnly: true
  mountOptions:
    - port={{ .Values.nfs.port }}
    - mountport={{ .Values.nfs.port }}
    - nfsvers=3
    - noacl
    - tcp
