// Copyright (C) The AetherFS Authors - All Rights Reserved
// See LICENSE for more information.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.17.3
// source: aetherfs/agent/v1/api.proto

package agentv1

import (
	v1 "github.com/mjpitz/aetherfs/api/aetherfs/dataset/v1"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// PublishRequest instructs the agent to publish the dataset found at the provided path with the associated tags.
type PublishRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Path string    `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	Tags []*v1.Tag `protobuf:"bytes,2,rep,name=tags,proto3" json:"tags,omitempty"`
}

func (x *PublishRequest) Reset() {
	*x = PublishRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_aetherfs_agent_v1_api_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PublishRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublishRequest) ProtoMessage() {}

func (x *PublishRequest) ProtoReflect() protoreflect.Message {
	mi := &file_aetherfs_agent_v1_api_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublishRequest.ProtoReflect.Descriptor instead.
func (*PublishRequest) Descriptor() ([]byte, []int) {
	return file_aetherfs_agent_v1_api_proto_rawDescGZIP(), []int{0}
}

func (x *PublishRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *PublishRequest) GetTags() []*v1.Tag {
	if x != nil {
		return x.Tags
	}
	return nil
}

// PublishResponse
type PublishResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *PublishResponse) Reset() {
	*x = PublishResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_aetherfs_agent_v1_api_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PublishResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublishResponse) ProtoMessage() {}

func (x *PublishResponse) ProtoReflect() protoreflect.Message {
	mi := &file_aetherfs_agent_v1_api_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublishResponse.ProtoReflect.Descriptor instead.
func (*PublishResponse) Descriptor() ([]byte, []int) {
	return file_aetherfs_agent_v1_api_proto_rawDescGZIP(), []int{1}
}

// SubscribeRequest is used to programmatically subscribe to dataset updates. Consumers can use this to get notified of
// when new versions of datasets become available.
type SubscribeRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Tag    *v1.Tag `protobuf:"bytes,1,opt,name=tag,proto3" json:"tag,omitempty"`
	Cancel bool    `protobuf:"varint,2,opt,name=cancel,proto3" json:"cancel,omitempty"`
}

func (x *SubscribeRequest) Reset() {
	*x = SubscribeRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_aetherfs_agent_v1_api_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SubscribeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribeRequest) ProtoMessage() {}

func (x *SubscribeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_aetherfs_agent_v1_api_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribeRequest.ProtoReflect.Descriptor instead.
func (*SubscribeRequest) Descriptor() ([]byte, []int) {
	return file_aetherfs_agent_v1_api_proto_rawDescGZIP(), []int{2}
}

func (x *SubscribeRequest) GetTag() *v1.Tag {
	if x != nil {
		return x.Tag
	}
	return nil
}

func (x *SubscribeRequest) GetCancel() bool {
	if x != nil {
		return x.Cancel
	}
	return false
}

// SubscribeResponse
type SubscribeResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Tag  *v1.Tag `protobuf:"bytes,1,opt,name=tag,proto3" json:"tag,omitempty"`
	Path string  `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
}

func (x *SubscribeResponse) Reset() {
	*x = SubscribeResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_aetherfs_agent_v1_api_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SubscribeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribeResponse) ProtoMessage() {}

func (x *SubscribeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_aetherfs_agent_v1_api_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribeResponse.ProtoReflect.Descriptor instead.
func (*SubscribeResponse) Descriptor() ([]byte, []int) {
	return file_aetherfs_agent_v1_api_proto_rawDescGZIP(), []int{3}
}

func (x *SubscribeResponse) GetTag() *v1.Tag {
	if x != nil {
		return x.Tag
	}
	return nil
}

func (x *SubscribeResponse) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

// GracefulShutdownRequest is used to initiate a graceful shutdown of the agent process. This will wait for all
// published datasets to be replicated before shutting down.
type GracefulShutdownRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GracefulShutdownRequest) Reset() {
	*x = GracefulShutdownRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_aetherfs_agent_v1_api_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GracefulShutdownRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GracefulShutdownRequest) ProtoMessage() {}

func (x *GracefulShutdownRequest) ProtoReflect() protoreflect.Message {
	mi := &file_aetherfs_agent_v1_api_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GracefulShutdownRequest.ProtoReflect.Descriptor instead.
func (*GracefulShutdownRequest) Descriptor() ([]byte, []int) {
	return file_aetherfs_agent_v1_api_proto_rawDescGZIP(), []int{4}
}

type GracefulShutdownResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GracefulShutdownResponse) Reset() {
	*x = GracefulShutdownResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_aetherfs_agent_v1_api_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GracefulShutdownResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GracefulShutdownResponse) ProtoMessage() {}

func (x *GracefulShutdownResponse) ProtoReflect() protoreflect.Message {
	mi := &file_aetherfs_agent_v1_api_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GracefulShutdownResponse.ProtoReflect.Descriptor instead.
func (*GracefulShutdownResponse) Descriptor() ([]byte, []int) {
	return file_aetherfs_agent_v1_api_proto_rawDescGZIP(), []int{5}
}

var File_aetherfs_agent_v1_api_proto protoreflect.FileDescriptor

var file_aetherfs_agent_v1_api_proto_rawDesc = []byte{
	0x0a, 0x1b, 0x61, 0x65, 0x74, 0x68, 0x65, 0x72, 0x66, 0x73, 0x2f, 0x61, 0x67, 0x65, 0x6e, 0x74,
	0x2f, 0x76, 0x31, 0x2f, 0x61, 0x70, 0x69, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x11, 0x61,
	0x65, 0x74, 0x68, 0x65, 0x72, 0x66, 0x73, 0x2e, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x2e, 0x76, 0x31,
	0x1a, 0x1d, 0x61, 0x65, 0x74, 0x68, 0x65, 0x72, 0x66, 0x73, 0x2f, 0x64, 0x61, 0x74, 0x61, 0x73,
	0x65, 0x74, 0x2f, 0x76, 0x31, 0x2f, 0x74, 0x61, 0x67, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a,
	0x1c, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x61, 0x6e, 0x6e, 0x6f,
	0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x52, 0x0a,
	0x0e, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x73, 0x68, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x12, 0x0a, 0x04, 0x70, 0x61, 0x74, 0x68, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x70,
	0x61, 0x74, 0x68, 0x12, 0x2c, 0x0a, 0x04, 0x74, 0x61, 0x67, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x18, 0x2e, 0x61, 0x65, 0x74, 0x68, 0x65, 0x72, 0x66, 0x73, 0x2e, 0x64, 0x61, 0x74,
	0x61, 0x73, 0x65, 0x74, 0x2e, 0x76, 0x31, 0x2e, 0x54, 0x61, 0x67, 0x52, 0x04, 0x74, 0x61, 0x67,
	0x73, 0x22, 0x11, 0x0a, 0x0f, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x73, 0x68, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x22, 0x56, 0x0a, 0x10, 0x53, 0x75, 0x62, 0x73, 0x63, 0x72, 0x69, 0x62,
	0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x2a, 0x0a, 0x03, 0x74, 0x61, 0x67, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x61, 0x65, 0x74, 0x68, 0x65, 0x72, 0x66, 0x73,
	0x2e, 0x64, 0x61, 0x74, 0x61, 0x73, 0x65, 0x74, 0x2e, 0x76, 0x31, 0x2e, 0x54, 0x61, 0x67, 0x52,
	0x03, 0x74, 0x61, 0x67, 0x12, 0x16, 0x0a, 0x06, 0x63, 0x61, 0x6e, 0x63, 0x65, 0x6c, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x08, 0x52, 0x06, 0x63, 0x61, 0x6e, 0x63, 0x65, 0x6c, 0x22, 0x53, 0x0a, 0x11,
	0x53, 0x75, 0x62, 0x73, 0x63, 0x72, 0x69, 0x62, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x2a, 0x0a, 0x03, 0x74, 0x61, 0x67, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x18,
	0x2e, 0x61, 0x65, 0x74, 0x68, 0x65, 0x72, 0x66, 0x73, 0x2e, 0x64, 0x61, 0x74, 0x61, 0x73, 0x65,
	0x74, 0x2e, 0x76, 0x31, 0x2e, 0x54, 0x61, 0x67, 0x52, 0x03, 0x74, 0x61, 0x67, 0x12, 0x12, 0x0a,
	0x04, 0x70, 0x61, 0x74, 0x68, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x70, 0x61, 0x74,
	0x68, 0x22, 0x19, 0x0a, 0x17, 0x47, 0x72, 0x61, 0x63, 0x65, 0x66, 0x75, 0x6c, 0x53, 0x68, 0x75,
	0x74, 0x64, 0x6f, 0x77, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x1a, 0x0a, 0x18,
	0x47, 0x72, 0x61, 0x63, 0x65, 0x66, 0x75, 0x6c, 0x53, 0x68, 0x75, 0x74, 0x64, 0x6f, 0x77, 0x6e,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x32, 0xed, 0x02, 0x0a, 0x08, 0x41, 0x67, 0x65,
	0x6e, 0x74, 0x41, 0x50, 0x49, 0x12, 0x72, 0x0a, 0x07, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x73, 0x68,
	0x12, 0x21, 0x2e, 0x61, 0x65, 0x74, 0x68, 0x65, 0x72, 0x66, 0x73, 0x2e, 0x61, 0x67, 0x65, 0x6e,
	0x74, 0x2e, 0x76, 0x31, 0x2e, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x73, 0x68, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x22, 0x2e, 0x61, 0x65, 0x74, 0x68, 0x65, 0x72, 0x66, 0x73, 0x2e, 0x61,
	0x67, 0x65, 0x6e, 0x74, 0x2e, 0x76, 0x31, 0x2e, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x73, 0x68, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x20, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x1a, 0x22,
	0x15, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x76, 0x31, 0x2f, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x2f, 0x70,
	0x75, 0x62, 0x6c, 0x69, 0x73, 0x68, 0x3a, 0x01, 0x2a, 0x12, 0x5c, 0x0a, 0x09, 0x53, 0x75, 0x62,
	0x73, 0x63, 0x72, 0x69, 0x62, 0x65, 0x12, 0x23, 0x2e, 0x61, 0x65, 0x74, 0x68, 0x65, 0x72, 0x66,
	0x73, 0x2e, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x2e, 0x76, 0x31, 0x2e, 0x53, 0x75, 0x62, 0x73, 0x63,
	0x72, 0x69, 0x62, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x24, 0x2e, 0x61, 0x65,
	0x74, 0x68, 0x65, 0x72, 0x66, 0x73, 0x2e, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x2e, 0x76, 0x31, 0x2e,
	0x53, 0x75, 0x62, 0x73, 0x63, 0x72, 0x69, 0x62, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x22, 0x00, 0x28, 0x01, 0x30, 0x01, 0x12, 0x8e, 0x01, 0x0a, 0x10, 0x47, 0x72, 0x61, 0x63,
	0x65, 0x66, 0x75, 0x6c, 0x53, 0x68, 0x75, 0x74, 0x64, 0x6f, 0x77, 0x6e, 0x12, 0x2a, 0x2e, 0x61,
	0x65, 0x74, 0x68, 0x65, 0x72, 0x66, 0x73, 0x2e, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x2e, 0x76, 0x31,
	0x2e, 0x47, 0x72, 0x61, 0x63, 0x65, 0x66, 0x75, 0x6c, 0x53, 0x68, 0x75, 0x74, 0x64, 0x6f, 0x77,
	0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x2b, 0x2e, 0x61, 0x65, 0x74, 0x68, 0x65,
	0x72, 0x66, 0x73, 0x2e, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x2e, 0x76, 0x31, 0x2e, 0x47, 0x72, 0x61,
	0x63, 0x65, 0x66, 0x75, 0x6c, 0x53, 0x68, 0x75, 0x74, 0x64, 0x6f, 0x77, 0x6e, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x21, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x1b, 0x22, 0x16, 0x2f,
	0x61, 0x70, 0x69, 0x2f, 0x76, 0x31, 0x2f, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x2f, 0x73, 0x68, 0x75,
	0x74, 0x64, 0x6f, 0x77, 0x6e, 0x3a, 0x01, 0x2a, 0x42, 0x75, 0x0a, 0x16, 0x74, 0x65, 0x63, 0x68,
	0x2e, 0x61, 0x65, 0x74, 0x68, 0x65, 0x72, 0x66, 0x73, 0x2e, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x2e,
	0x76, 0x31, 0x42, 0x08, 0x41, 0x50, 0x49, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x50, 0x01, 0x5a, 0x38,
	0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6d, 0x6a, 0x70, 0x69, 0x74,
	0x7a, 0x2f, 0x61, 0x65, 0x74, 0x68, 0x65, 0x72, 0x66, 0x73, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x61,
	0x65, 0x74, 0x68, 0x65, 0x72, 0x66, 0x73, 0x2f, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x2f, 0x76, 0x31,
	0x3b, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x76, 0x31, 0xa0, 0x01, 0x01, 0xaa, 0x02, 0x11, 0x41, 0x65,
	0x74, 0x68, 0x65, 0x72, 0x46, 0x53, 0x2e, 0x41, 0x67, 0x65, 0x6e, 0x74, 0x2e, 0x56, 0x31, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_aetherfs_agent_v1_api_proto_rawDescOnce sync.Once
	file_aetherfs_agent_v1_api_proto_rawDescData = file_aetherfs_agent_v1_api_proto_rawDesc
)

func file_aetherfs_agent_v1_api_proto_rawDescGZIP() []byte {
	file_aetherfs_agent_v1_api_proto_rawDescOnce.Do(func() {
		file_aetherfs_agent_v1_api_proto_rawDescData = protoimpl.X.CompressGZIP(file_aetherfs_agent_v1_api_proto_rawDescData)
	})
	return file_aetherfs_agent_v1_api_proto_rawDescData
}

var file_aetherfs_agent_v1_api_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_aetherfs_agent_v1_api_proto_goTypes = []interface{}{
	(*PublishRequest)(nil),           // 0: aetherfs.agent.v1.PublishRequest
	(*PublishResponse)(nil),          // 1: aetherfs.agent.v1.PublishResponse
	(*SubscribeRequest)(nil),         // 2: aetherfs.agent.v1.SubscribeRequest
	(*SubscribeResponse)(nil),        // 3: aetherfs.agent.v1.SubscribeResponse
	(*GracefulShutdownRequest)(nil),  // 4: aetherfs.agent.v1.GracefulShutdownRequest
	(*GracefulShutdownResponse)(nil), // 5: aetherfs.agent.v1.GracefulShutdownResponse
	(*v1.Tag)(nil),                   // 6: aetherfs.dataset.v1.Tag
}
var file_aetherfs_agent_v1_api_proto_depIdxs = []int32{
	6, // 0: aetherfs.agent.v1.PublishRequest.tags:type_name -> aetherfs.dataset.v1.Tag
	6, // 1: aetherfs.agent.v1.SubscribeRequest.tag:type_name -> aetherfs.dataset.v1.Tag
	6, // 2: aetherfs.agent.v1.SubscribeResponse.tag:type_name -> aetherfs.dataset.v1.Tag
	0, // 3: aetherfs.agent.v1.AgentAPI.Publish:input_type -> aetherfs.agent.v1.PublishRequest
	2, // 4: aetherfs.agent.v1.AgentAPI.Subscribe:input_type -> aetherfs.agent.v1.SubscribeRequest
	4, // 5: aetherfs.agent.v1.AgentAPI.GracefulShutdown:input_type -> aetherfs.agent.v1.GracefulShutdownRequest
	1, // 6: aetherfs.agent.v1.AgentAPI.Publish:output_type -> aetherfs.agent.v1.PublishResponse
	3, // 7: aetherfs.agent.v1.AgentAPI.Subscribe:output_type -> aetherfs.agent.v1.SubscribeResponse
	5, // 8: aetherfs.agent.v1.AgentAPI.GracefulShutdown:output_type -> aetherfs.agent.v1.GracefulShutdownResponse
	6, // [6:9] is the sub-list for method output_type
	3, // [3:6] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_aetherfs_agent_v1_api_proto_init() }
func file_aetherfs_agent_v1_api_proto_init() {
	if File_aetherfs_agent_v1_api_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_aetherfs_agent_v1_api_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PublishRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_aetherfs_agent_v1_api_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PublishResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_aetherfs_agent_v1_api_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SubscribeRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_aetherfs_agent_v1_api_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SubscribeResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_aetherfs_agent_v1_api_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GracefulShutdownRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_aetherfs_agent_v1_api_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GracefulShutdownResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_aetherfs_agent_v1_api_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_aetherfs_agent_v1_api_proto_goTypes,
		DependencyIndexes: file_aetherfs_agent_v1_api_proto_depIdxs,
		MessageInfos:      file_aetherfs_agent_v1_api_proto_msgTypes,
	}.Build()
	File_aetherfs_agent_v1_api_proto = out.File
	file_aetherfs_agent_v1_api_proto_rawDesc = nil
	file_aetherfs_agent_v1_api_proto_goTypes = nil
	file_aetherfs_agent_v1_api_proto_depIdxs = nil
}
